# Builtin KingMC Config

# The version of current config
# DO NOT CHANGE
config-version: 1

kingmc:
  # Flag to enable bootstrap when kingmc first setup on your server
  # After the kingmc bootstrap is complete, you can enable it to run the kingmc bootstrap again on the server to set up kingmc
  bootstrap: true

  # Environment settings
  environment:
    # The default maven repository to download dependencies from
    # For instance: https://repo1.maven.org/maven2/ (Maven central repository)
    #
    # If your server is located in China you can use the mirror repository down below
    # https://maven.aliyun.com/repository/public/
    maven-repository: https://repo1.maven.org/maven2/

    # Kotlin version
    kotlin: 1.9.0

    # Kotlin coroutine version
    kotlinx-coroutine: 1.6.4

  # Extensions settings
  extensions:
    # If enabled, kingmc will automatically download dependent extensions
    # required by installed extensions
    auto-download:
      # Enable auto-download
      enable: true

      # The source to download missing extensions from
      # KingMC - Download missing extensions (by id declared) from kingmc forum (https://www.kingmc.net/)
      # URL - Download missing extensions (by url declared) from specified url
      source: [url, kingmc]

      # A black list of extensions, so kingmc won't automatically download them
      blacklist:
        - some_extension # Extension id

    # Extension bundling settings
    bundling:
      # Enable so kingmc will try to download bundled extensions and load them on the server
      enable: true

      # Extensions bundled
      toolbox:
        # The ways to load this extension
        # Builtin - load the extension from specified file that already builtin the kingmc jar
        # URL - download the extension from specified url, the extension file downloaded will be stored in kingmc extension folder
        load: [url, builtin]

        # The built-in extension file path to load extension from if you're using "Builtin" to load bundled extension
        path: "/bundle/toolbox-latest.jar"

        # The extension file url to download extension from if you're using "URL" to load bundled extension
        url: "https://www.kingmc.net/resources/kingsthere/toolbox/latest.jar"