# Builtin KingMC Config

# The version of current config
# DO NOT CHANGE
config-version: 1

kingmc:
  # Flag to enable bootstrap when kingmc first setup on your server
  # After the kingmc bootstrap is complete, you can enable it to run the kingmc bootstrap again on the server to set up kingmc
  bootstrap: true

  # Environment settings
  environment:
    # The default maven repository to download dependencies from
    # For instance: https://repo1.maven.org/maven2/ (Maven central repository)
    #
    # If your server is located in China you can use the mirror repository down below
    # https://maven.aliyun.com/repository/public/
    maven-repository: https://repo1.maven.org/maven2/

    # Kotlin version
    kotlin: 1.8.10

    # Kotlin coroutine version
    kotlinx-coroutine: 1.6.4

  # Extension bundling settings
  bundling:
    # Enable so kingmc will try to download bundled extensions and load them on the server
    enable: true

    # Extensions bundled
    extensions:
      toolbox:
        # The way to load this extension
        # Builtin - load the extension from specified file that already builtin the kingmc jar
        # URL - download the extension from specified url, the extension file downloaded will be stored in kingmc extension folder
        load: url

        # The built-in extension file path to load extension from if you're using "Builtin" to load bundled extension
        path: "/bundle/toolbox-latest.jar"

        # The extension file url to download extension from if you're using "URL" to load bundled extension
        url: "https://www.kingmc.net/resources/kingsthere/toolbox/latest.jar"