package kingmc.platform.entity

import kingmc.util.key.Key
import kingmc.util.key.Keyed

/**
 * Superinterface determine a type of entity that registered on this server
 *
 * @param TEntity the type of entity this type supports
 * @since 0.0.7
 * @author kingsthere
 */
interface EntityType<TEntity : Entity> : Keyed {
    /**
     * The key of this entity type
     */
    override val key: Key

    companion object {
        // val DROPPED_ITEM: EntityType<Item> = EntityType(Key("minecraft:item"))
        // val EXPERIENCE_ORB: EntityType<ExperienceOrb> = EntityType(Key("minecraft:experience_orb"))
        // val AREA_EFFECT_CLOUD: EntityType<AreaEffectCloud> = EntityType(Key("minecraft:area_effect_cloud"))
        // val ELDER_GUARDIAN: EntityType<ElderGuardian> = EntityType(Key("minecraft:elder_guardian"))
        // val WITHER_SKELETON: EntityType<WitherSkeleton> = EntityType(Key("minecraft:wither_skeleton"))
        // val STRAY: EntityType<Stray> = EntityType(Key("minecraft:stray"))
        // val EGG: EntityType<Egg> = EntityType(Key("minecraft:egg"))
        // val LEASH_HITCH: EntityType<LeashHitch> = EntityType(Key("minecraft:leash_knot"))
        // val PAINTING: EntityType<Painting> = EntityType(Key("minecraft:painting"))
        // val ARROW: EntityType<Arrow> = EntityType(Key("minecraft:arrow"))
        // val SNOWBALL: EntityType<Snowball> = EntityType(Key("minecraft:snowball"))
        // val FIREBALL: EntityType<LargeFireball> = EntityType(Key("minecraft:fireball"))
        // val SMALL_FIREBALL: EntityType<SmallFireball> = EntityType(Key("minecraft:small_fireball"))
        // val ENDER_PEARL: EntityType<EnderPearl> = EntityType(Key("minecraft:ender_pearl"))
        // val ENDER_SIGNAL: EntityType<EnderSignal> = EntityType(Key("minecraft:eye_of_ender"))
        // val SPLASH_POTION: EntityType<ThrownPotion> = EntityType(Key("minecraft:potion"))
        // val THROWN_EXP_BOTTLE: EntityType<ThrownExpBottle> = EntityType(Key("minecraft:experience_bottle"))
        // val ITEM_FRAME: EntityType<ItemFrame> = EntityType(Key("minecraft:item_frame"))
        // val WITHER_SKULL: EntityType<WitherSkull> = EntityType(Key("minecraft:wither_skull"))
        // val PRIMED_TNT: EntityType<TNTPrimed> = EntityType(Key("minecraft:tnt"))
        // val FALLING_BLOCK: EntityType<FallingBlock> = EntityType(Key("minecraft:falling_block"))
        // val FIREWORK: EntityType<Firework> = EntityType(Key("minecraft:firework_rocket"))
        // val HUSK: EntityType<Husk> = EntityType(Key("minecraft:husk"))
        // val SPECTRAL_ARROW: EntityType<SpectralArrow> = EntityType(Key("minecraft:spectral_arrow"))
        // val SHULKER_BULLET: EntityType<ShulkerBullet> = EntityType(Key("minecraft:shulker_bullet"))
        // val DRAGON_FIREBALL: EntityType<DragonFireball> = EntityType(Key("minecraft:dragon_fireball"))
        // val ZOMBIE_VILLAGER: EntityType<ZombieVillager> = EntityType(Key("minecraft:zombie_villager"))
        // val SKELETON_HORSE: EntityType<SkeletonHorse> = EntityType(Key("minecraft:skeleton_horse"))
        // val ZOMBIE_HORSE: EntityType<ZombieHorse> = EntityType(Key("minecraft:zombie_horse"))
        // val ARMOR_STAND: EntityType<ArmorStand> = EntityType(Key("minecraft:armor_stand"))
        // val DONKEY: EntityType<Donkey> = EntityType(Key("minecraft:donkey"))
        // val MULE: EntityType<Mule> = EntityType(Key("minecraft:mule"))
        // val EVOKER_FANGS: EntityType<EvokerFangs> = EntityType(Key("minecraft:evoker_fangs"))
        // val EVOKER: EntityType<Evoker> = EntityType(Key("minecraft:evoker"))
        // val VEX: EntityType<Vex> = EntityType(Key("minecraft:vex"))
        // val VINDICATOR: EntityType<Vindicator> = EntityType(Key("minecraft:vindicator"))
        // val ILLUSIONER: EntityType<Illusioner> = EntityType(Key("minecraft:illusioner"))
        // val MINECART_COMMAND: EntityType<CommandMinecart> = EntityType(Key("minecraft:command_block_minecart"))
        // val BOAT: EntityType<Boat> = EntityType(Key("minecraft:boat"))
        // val MINECART: EntityType<RideableMinecart> = EntityType(Key("minecraft:minecart"))
        // val MINECART_CHEST: EntityType<StorageMinecart> = EntityType(Key("minecraft:chest_minecart"))
        // val MINECART_FURNACE: EntityType<PoweredMinecart> = EntityType(Key("minecraft:furnace_minecart"))
        // val MINECART_TNT: EntityType<ExplosiveMinecart> = EntityType(Key("minecraft:tnt_minecart"))
        // val MINECART_HOPPER: EntityType<HopperMinecart> = EntityType(Key("minecraft:hopper_minecart"))
        // val MINECART_MOB_SPAWNER: EntityType<SpawnerMinecart> = EntityType(Key("minecraft:spawner_minecart"))
        // val CREEPER: EntityType<Creeper> = EntityType(Key("minecraft:creeper"))
        // val SKELETON: EntityType<Skeleton> = EntityType(Key("minecraft:skeleton"))
        // val SPIDER: EntityType<Spider> = EntityType(Key("minecraft:spider"))
        // val GIANT: EntityType<Giant> = EntityType(Key("minecraft:giant"))
        // val ZOMBIE: EntityType<Zombie> = EntityType(Key("minecraft:zombie"))
        // val SLIME: EntityType<Slime> = EntityType(Key("minecraft:slime"))
        // val GHAST: EntityType<Ghast> = EntityType(Key("minecraft:ghast"))
        // val ZOMBIFIED_PIGLIN: EntityType<PigZombie> = EntityType(Key("minecraft:zombified_piglin"))
        // val ENDERMAN: EntityType<Enderman> = EntityType(Key("minecraft:enderman"))
        // val CAVE_SPIDER: EntityType<CaveSpider> = EntityType(Key("minecraft:cave_spider"))
        // val SILVERFISH: EntityType<Silverfish> = EntityType(Key("minecraft:silverfish"))
        // val BLAZE: EntityType<Blaze> = EntityType(Key("minecraft:blaze"))
        // val MAGMA_CUBE: EntityType<MagmaCube> = EntityType(Key("minecraft:magma_cube"))
        // val ENDER_DRAGON: EntityType<EnderDragon> = EntityType(Key("minecraft:ender_dragon"))
        // val WITHER: EntityType<Wither> = EntityType(Key("minecraft:wither"))
        // val BAT: EntityType<Bat> = EntityType(Key("minecraft:bat"))
        // val WITCH: EntityType<Witch> = EntityType(Key("minecraft:witch"))
        // val ENDERMITE: EntityType<Endermite> = EntityType(Key("minecraft:endermite"))
        // val GUARDIAN: EntityType<Guardian> = EntityType(Key("minecraft:guardian"))
        // val SHULKER: EntityType<Shulker> = EntityType(Key("minecraft:shulker"))
        // val PIG: EntityType<Pig> = EntityType(Key("minecraft:pig"))
        // val SHEEP: EntityType<Sheep> = EntityType(Key("minecraft:sheep"))
        // val COW: EntityType<Cow> = EntityType(Key("minecraft:cow"))
        // val CHICKEN: EntityType<Chicken> = EntityType(Key("minecraft:chicken"))
        // val SQUID: EntityType<Squid> = EntityType(Key("minecraft:squid"))
        // val WOLF: EntityType<Wolf> = EntityType(Key("minecraft:wolf"))
        // val MUSHROOM_COW: EntityType<MushroomCow> = EntityType(Key("minecraft:mooshroom"))
        // val SNOWMAN: EntityType<Snowman> = EntityType(Key("minecraft:snow_golem"))
        // val OCELOT: EntityType<Ocelot> = EntityType(Key("minecraft:ocelot"))
        // val IRON_GOLEM: EntityType<IronGolem> = EntityType(Key("minecraft:iron_golem"))
        // val HORSE: EntityType<Horse> = EntityType(Key("minecraft:horse"))
        // val RABBIT: EntityType<Rabbit> = EntityType(Key("minecraft:rabbit"))
        // val POLAR_BEAR: EntityType<PolarBear> = EntityType(Key("minecraft:polar_bear"))
        // val LLAMA: EntityType<Llama> = EntityType(Key("minecraft:llama"))
        // val LLAMA_SPIT: EntityType<LlamaSpit> = EntityType(Key("minecraft:llama_spit"))
        // val PARROT: EntityType<Parrot> = EntityType(Key("minecraft:parrot"))
        // val VILLAGER: EntityType<Villager> = EntityType(Key("minecraft:villager"))
        // val ENDER_CRYSTAL: EntityType<EnderCrystal> = EntityType(Key("minecraft:end_crystal"))
        // val TURTLE: EntityType<Turtle> = EntityType(Key("minecraft:turtle"))
        // val PHANTOM: EntityType<Phantom> = EntityType(Key("minecraft:phantom"))
        // val TRIDENT: EntityType<Trident> = EntityType(Key("minecraft:trident"))
        // val COD: EntityType<Cod> = EntityType(Key("minecraft:cod"))
        // val SALMON: EntityType<Salmon> = EntityType(Key("minecraft:salmon"))
        // val PUFFERFISH: EntityType<PufferFish> = EntityType(Key("minecraft:pufferfish"))
        // val TROPICAL_FISH: EntityType<TropicalFish> = EntityType(Key("minecraft:tropical_fish"))
        // val DROWNED: EntityType<Drowned> = EntityType(Key("minecraft:drowned"))
        // val DOLPHIN: EntityType<Dolphin> = EntityType(Key("minecraft:dolphin"))
        // val CAT: EntityType<Cat> = EntityType(Key("minecraft:cat"))
        // val PANDA: EntityType<Panda> = EntityType(Key("minecraft:panda"))
        // val PILLAGER: EntityType<Pillager> = EntityType(Key("minecraft:pillager"))
        // val RAVAGER: EntityType<Ravager> = EntityType(Key("minecraft:ravager"))
        // val TRADER_LLAMA: EntityType<TraderLlama> = EntityType(Key("minecraft:trader_llama"))
        // val WANDERING_TRADER: EntityType<WanderingTrader> = EntityType(Key("minecraft:wandering_trader"))
        // val FOX: EntityType<Fox> = EntityType(Key("minecraft:fox"))
        // val BEE: EntityType<Bee> = EntityType(Key("minecraft:bee"))
        // val HOGLIN: EntityType<Hoglin> = EntityType(Key("minecraft:hoglin"))
        // val PIGLIN: EntityType<Piglin> = EntityType(Key("minecraft:piglin"))
        // val STRIDER: EntityType<Strider> = EntityType(Key("minecraft:strider"))
        // val ZOGLIN: EntityType<Zoglin> = EntityType(Key("minecraft:zoglin"))
        // val PIGLIN_BRUTE: EntityType<PiglinBrute> = EntityType(Key("minecraft:piglin_brute"))
        // val AXOLOTL: EntityType<Axolotl> = EntityType(Key("minecraft:axolotl"))
        // val GLOW_ITEM_FRAME: EntityType<GlowItemFrame> = EntityType(Key("minecraft:glow_item_frame"))
        // val GLOW_SQUID: EntityType<GlowSquid> = EntityType(Key("minecraft:glow_squid"))
        // val GOAT: EntityType<Goat> = EntityType(Key("minecraft:goat"))
        // val MARKER: EntityType<Marker> = EntityType(Key("minecraft:marker"))
        // val ALLAY: EntityType<Allay> = EntityType(Key("minecraft:allay"))
        // val CHEST_BOAT: EntityType<ChestBoat> = EntityType(Key("minecraft:chest_boat"))
        // val FROG: EntityType<Frog> = EntityType(Key("minecraft:frog"))
        // val TADPOLE: EntityType<Tadpole> = EntityType(Key("minecraft:tadpole"))
        // val WARDEN: EntityType<Warden> = EntityType(Key("minecraft:warden"))
        // val CAMEL: EntityType<Camel> = EntityType(Key("minecraft:camel"))
        // val FISHING_HOOK: EntityType<FishHook> = EntityType(Key("minecraft:fishing_bobber"))
        // val LIGHTNING: EntityType<LightningStrike> = EntityType(Key("minecraft:lightning_bolt"))
        // val PLAYER: EntityType<Player> = EntityType(Key("minecraft:player"))
    }
}