package kingmc.platform.entity

import kingmc.util.key.Key
import kingmc.util.key.Keyed

/**
 * Superinterface determine a type of entity that registered on this server
 *
 * @author kingsthere
 * @since 0.0.7
 */
interface EntityType : Keyed {
    /**
     * The key of this entity type
     */
    override val key: Key

    companion object {
         val DROPPED_ITEM: Key = Key("minecraft:item")
         val EXPERIENCE_ORB: Key = Key("minecraft:experience_orb")
         val AREA_EFFECT_CLOUD: Key = Key("minecraft:area_effect_cloud")
         val ELDER_GUARDIAN: Key = Key("minecraft:elder_guardian")
         val WITHER_SKELETON: Key = Key("minecraft:wither_skeleton")
         val STRAY: Key = Key("minecraft:stray")
         val EGG: Key = Key("minecraft:egg")
         val LEASH_HITCH: Key = Key("minecraft:leash_knot")
         val PAINTING: Key = Key("minecraft:painting")
         val ARROW: Key = Key("minecraft:arrow")
         val SNOWBALL: Key = Key("minecraft:snowball")
         val FIREBALL: Key = Key("minecraft:fireball")
         val SMALL_FIREBALL: Key = Key("minecraft:small_fireball")
         val ENDER_PEARL: Key = Key("minecraft:ender_pearl")
         val ENDER_SIGNAL: Key = Key("minecraft:eye_of_ender")
         val SPLASH_POTION: Key = Key("minecraft:potion")
         val THROWN_EXP_BOTTLE: Key = Key("minecraft:experience_bottle")
         val ITEM_FRAME: Key = Key("minecraft:item_frame")
         val WITHER_SKULL: Key = Key("minecraft:wither_skull")
         val PRIMED_TNT: Key = Key("minecraft:tnt")
         val FALLING_BLOCK: Key = Key("minecraft:falling_block")
         val FIREWORK: Key = Key("minecraft:firework_rocket")
         val HUSK: Key = Key("minecraft:husk")
         val SPECTRAL_ARROW: Key = Key("minecraft:spectral_arrow")
         val SHULKER_BULLET: Key = Key("minecraft:shulker_bullet")
         val DRAGON_FIREBALL: Key = Key("minecraft:dragon_fireball")
         val ZOMBIE_VILLAGER: Key = Key("minecraft:zombie_villager")
         val SKELETON_HORSE: Key = Key("minecraft:skeleton_horse")
         val ZOMBIE_HORSE: Key = Key("minecraft:zombie_horse")
         val ARMOR_STAND: Key = Key("minecraft:armor_stand")
         val DONKEY: Key = Key("minecraft:donkey")
         val MULE: Key = Key("minecraft:mule")
         val EVOKER_FANGS: Key = Key("minecraft:evoker_fangs")
         val EVOKER: Key = Key("minecraft:evoker")
         val VEX: Key = Key("minecraft:vex")
         val VINDICATOR: Key = Key("minecraft:vindicator")
         val ILLUSIONER: Key = Key("minecraft:illusioner")
         val MINECART_COMMAND: Key = Key("minecraft:command_block_minecart")
         val BOAT: Key = Key("minecraft:boat")
         val MINECART: Key = Key("minecraft:minecart")
         val MINECART_CHEST: Key = Key("minecraft:chest_minecart")
         val MINECART_FURNACE: Key = Key("minecraft:furnace_minecart")
         val MINECART_TNT: Key = Key("minecraft:tnt_minecart")
         val MINECART_HOPPER: Key = Key("minecraft:hopper_minecart")
         val MINECART_MOB_SPAWNER: Key = Key("minecraft:spawner_minecart")
         val CREEPER: Key = Key("minecraft:creeper")
         val SKELETON: Key = Key("minecraft:skeleton")
         val SPIDER: Key = Key("minecraft:spider")
         val GIANT: Key = Key("minecraft:giant")
         val ZOMBIE: Key = Key("minecraft:zombie")
         val SLIME: Key = Key("minecraft:slime")
         val GHAST: Key = Key("minecraft:ghast")
         val ZOMBIFIED_PIGLIN: Key = Key("minecraft:zombified_piglin")
         val ENDERMAN: Key = Key("minecraft:enderman")
         val CAVE_SPIDER: Key = Key("minecraft:cave_spider")
         val SILVERFISH: Key = Key("minecraft:silverfish")
         val BLAZE: Key = Key("minecraft:blaze")
         val MAGMA_CUBE: Key = Key("minecraft:magma_cube")
         val ENDER_DRAGON: Key = Key("minecraft:ender_dragon")
         val WITHER: Key = Key("minecraft:wither")
         val BAT: Key = Key("minecraft:bat")
         val WITCH: Key = Key("minecraft:witch")
         val ENDERMITE: Key = Key("minecraft:endermite")
         val GUARDIAN: Key = Key("minecraft:guardian")
         val SHULKER: Key = Key("minecraft:shulker")
         val PIG: Key = Key("minecraft:pig")
         val SHEEP: Key = Key("minecraft:sheep")
         val COW: Key = Key("minecraft:cow")
         val CHICKEN: Key = Key("minecraft:chicken")
         val SQUID: Key = Key("minecraft:squid")
         val WOLF: Key = Key("minecraft:wolf")
         val MUSHROOM_COW: Key = Key("minecraft:mooshroom")
         val SNOWMAN: Key = Key("minecraft:snow_golem")
         val OCELOT: Key = Key("minecraft:ocelot")
         val IRON_GOLEM: Key = Key("minecraft:iron_golem")
         val HORSE: Key = Key("minecraft:horse")
         val RABBIT: Key = Key("minecraft:rabbit")
         val POLAR_BEAR: Key = Key("minecraft:polar_bear")
         val LLAMA: Key = Key("minecraft:llama")
         val LLAMA_SPIT: Key = Key("minecraft:llama_spit")
         val PARROT: Key = Key("minecraft:parrot")
         val VILLAGER: Key = Key("minecraft:villager")
         val ENDER_CRYSTAL: Key = Key("minecraft:end_crystal")
         val TURTLE: Key = Key("minecraft:turtle")
         val PHANTOM: Key = Key("minecraft:phantom")
         val TRIDENT: Key = Key("minecraft:trident")
         val COD: Key = Key("minecraft:cod")
         val SALMON: Key = Key("minecraft:salmon")
         val PUFFERFISH: Key = Key("minecraft:pufferfish")
         val TROPICAL_FISH: Key = Key("minecraft:tropical_fish")
         val DROWNED: Key = Key("minecraft:drowned")
         val DOLPHIN: Key = Key("minecraft:dolphin")
         val CAT: Key = Key("minecraft:cat")
         val PANDA: Key = Key("minecraft:panda")
         val PILLAGER: Key = Key("minecraft:pillager")
         val RAVAGER: Key = Key("minecraft:ravager")
         val TRADER_LLAMA: Key = Key("minecraft:trader_llama")
         val WANDERING_TRADER: Key = Key("minecraft:wandering_trader")
         val FOX: Key = Key("minecraft:fox")
         val BEE: Key = Key("minecraft:bee")
         val HOGLIN: Key = Key("minecraft:hoglin")
         val PIGLIN: Key = Key("minecraft:piglin")
         val STRIDER: Key = Key("minecraft:strider")
         val ZOGLIN: Key = Key("minecraft:zoglin")
         val PIGLIN_BRUTE: Key = Key("minecraft:piglin_brute")
         val AXOLOTL: Key = Key("minecraft:axolotl")
         val GLOW_ITEM_FRAME: Key = Key("minecraft:glow_item_frame")
         val GLOW_SQUID: Key = Key("minecraft:glow_squid")
         val GOAT: Key = Key("minecraft:goat")
         val MARKER: Key = Key("minecraft:marker")
         val ALLAY: Key = Key("minecraft:allay")
         val CHEST_BOAT: Key = Key("minecraft:chest_boat")
         val FROG: Key = Key("minecraft:frog")
         val TADPOLE: Key = Key("minecraft:tadpole")
         val WARDEN: Key = Key("minecraft:warden")
         val CAMEL: Key = Key("minecraft:camel")
         val FISHING_HOOK: Key = Key("minecraft:fishing_bobber")
         val LIGHTNING: Key = Key("minecraft:lightning_bolt")
         val PLAYER: Key = Key("minecraft:player")
    }
}
